spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${github-client-id}
            client-secret: ${github-client-secret}
#            scope:
#              - openid
#              - profile
#              - email
          google:
            client-id: ${google-client-id}
            client-secret: ${google-client-secret}
            scope:
              - openid
              - profile
              - email
          facebook:
            client-id: ${facebook-client-id}
            client-secret: ${facebook-client-secret}